export const STUDENTS_GET = "STUDENTS_GET";
export const STUDENT_GET = "STUDENT_GET";
export const STUDENT_ADD = "STUDENT_ADD";
export const STUDENT_EDIT = "STUDENT_EDIT";
export const STUDENT_DELETE = "STUDENT_DELETE";
export const STUDENT_ERROR = "STUDENT_ERROR";

export const UNDERGRADUATES_GET = "UNDERGRADUATES_GET";
export const UNDERGRADUATE_GET = "UNDERGRADUATE_GET";
export const UNDERGRADUATE_ADD = "UNDERGRADUATE_ADD";
export const UNDERGRADUATE_EDIT = "UNDERGRADUATE_EDIT";
export const UNDERGRADUATE_DELETE = "UNDERGRADUATE_DELETE";
export const UNDERGRADUATE_ERROR = "UNDERGRADUATE_ERROR";
